apiVersion: v1
kind: Service
metadata:
  # This name uniquely identifies the service
  name: minio-service
spec:
  type: NodePort
  ports:
  - port: 9001
    targetPort: 9000
    nodePort: 32001
    protocol: TCP
  selector:
    # Looks for labels `app:minio` in the namespace and applies the spec
    app: minio